### ISSUE TITLE
Add Contributors

### ISSUE THREAD

**Issue by berrysauce** [StopModReposts/Extension#11]

**Comment by berrysauce** [comment]
@all-contributors please add @dada513 for code, ideas, maintenance, translation, test

**Comment by berrysauce** [comment]
@all-contributors please add RazrCraft for translation

**Comment by berrysauce** [comment]
@all-contributors please add "RazrCraft" for translation

**Comment by R4z0rX** [comment]
Lol, I'm RazrCraft 😋
